### ISSUE TITLE
Invalid return from Lambda handlers?

### ISSUE THREAD

**Issue by phillipj** [ahrefs/bs-aws-lambda#16]
I'm still very much a Reason-rookie, so please excuse me if I'm doing something really odd here..

Having a little difficulty using these types to create Lambda functions. A trivial example to demonstrate what I'm struggling with:

```reason
open AwsLambda.APIGatewayProxy

let hello: handler = (_event, _context, cb) => {
  let body = result(~body=`Plain("Hello there!"), ~statusCode=201, ());

  cb(Js.null, body);
  Js.Promise.resolve();
}
```

Requesting this handler returns an empty body with 200 status code. Thinking about how Lambdas work from a pure JavaScript point of view, it either expects the provided callback to be invoked with the response **or** a promise returned with the response. Therefore the experienced behaviour kind of makes sense.

The following examples work as expected though. I'm unsure what would be ideal reason-esque.

#### 1) Invoking the callback uncurried

```reason
open AwsLambda.APIGatewayProxy

let hello = (_event, _context, cb) => {
  let body = result(~body=`Plain("Hello there!"), ~statusCode=201, ());

  [@bs] cb(Js.null, body);
}
```

#### 2) Returning a promise

```reason
open AwsLambda.APIGatewayProxy

let hello = (_event, _context) => {
  let body = result(~body=`Plain("Hello there!"), ~statusCode=201, ());

  Js.Promise.resolve(body);
}
```

Guess this all boils down to the common handler definition below, where the return type should be `unit` or the promise's value be `Js.Promise.t('return)`?

```reason
type handler('event, 'error, 'return) =
  ('event, Context.t, callback('error, 'return)) => Js.Promise.t(unit);
```

**Comment by Khady** [comment]
I am wondering if annotating the callback type would work. I am a bit surprised because I have production code that use the first example and works fine too. But maybe because it is with an older version of bucklescript. I can't remember how I reached this type for the handler. Reading https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html again I think you are right and something must be changed.

Would you like to provide a PR?

**Comment by phillipj** [comment]
Sorry for the late reply, been travelling and currently on a conference.

Thanks for your thoughts! I opened a work in progress PR (#17) where we can continue this discussion, therefore closing this issue for now.
