### ISSUE TITLE
Example of an authorizer function?

### ISSUE THREAD

**Issue by johnhaley81** [ahrefs/bs-aws-lambda#2]
Thanks for the great types!

I was wondering if you had an example of how you'd write an authorizer function with these types? I think there might be some things missing for that.

**Comment by Khady** [comment]
Are you talking about https://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html?

I will see what is missing.

**Comment by johnhaley81** [comment]
The event that's sent in is not the same. It has `event.authorizationToken` which is where you can get the auth token from the header, and not `event##headers` which doesn't exist in the custom auth function.

**Comment by johnhaley81** [comment]
The shape of the event passed into the auth function is:

```
{
  type: 'TOKEN', // I don't know all of the different strings that could be passed in this field.
  methodArn: 'some:arn:for:the:method',
  authorizationToken: 'Bearer sometoken'
}
```
