### ISSUE TITLE
Switch out `any` type for built in `Js.Json.t`

### ISSUE THREAD

**Issue by johnhaley81** [ahrefs/bs-aws-lambda#7]
Reason has a built in "any" type `Js.Json.t` that allows for a safe way to decode something that comes in from javascript.

Instead of doing an unsafe `"%identity"` cast that allows unsound code, `Js.Json.t` will provide you decode errors that will tell you what you expected and what you received and won't allow you to write unsound code.

**Comment by Khady** [comment]
Sounds right. I can't remember why I used identity instead of `Js.Json.t`. Would you mind providing a PR?

**Comment by johnhaley81** [comment]
Np. I just opened #11
